### ISSUE TITLE
Show Image Option doesn't work

### ISSUE THREAD

**Issue by qvc444** [rkokkelk/nl.xseth.dashboardctrl#10]
Hello Roy,
The View Image option from cameras no longer works via Fully Browser.
When performed, only a red exclamation mark. 
URL and dashboard views are fine. Onvif app shows all cameras. 
Error possibly since update to Homey 7.4.1 but I'm not sure.

**Comment by rkokkelk** [comment]
Error:

```
Cannot read properties of undefined (reading 'getLocalAddress')
```

**Comment by qvc444** [comment]
Hello Roy.
Thanks for the quick fix.
It feels better than before.
