### ISSUE TITLE
Fully browser connectivity not properly detected

### ISSUE THREAD

**Issue by rkokkelk** [rkokkelk/nl.xseth.dashboardctrl#2]
When fully browser device is turned offline and the online again, the new status is not properly detected by the app. This results in the device in homey staying unavailable.

**Comment by m4xx75** [comment]
Hello,

I had the same problem in version 0.1.5. The only way was to remove the device and recreate it. I tried to reboot the App, change the session settings to reset it, but nothing worked.
Maxx

**Comment by m4xx75** [comment]
the connection was lost this morning around 3:30 AM, but maybe the logs are still available:
2a22c7d3-3b13-464d-acb2-7050d6460526
