### ISSUE TITLE
Homey Bridge

### ISSUE THREAD

**Issue by AdrianOstus** [rkokkelk/nl.xseth.dashboardctrl#9]
This app is not running in the Homey cloud and therefore its not possible to run it with Homey bridge. Any chance this app will run in Homey cloud in the future?

**Comment by rkokkelk** [comment]
My apologies for the late reply, kinda missed this one. But to my understanding the Homey bridge does not allow for LAN connections. So it would not be possible to connect from the bridge to the local Fully Kiosk app. This is quite mandatory and do not see any other implementation possible. So as long as this restriction is present this app will not work in the Homey cloud.
